#!/bin/sh

printf "\n--- /etc/devscripts.conf ---\n" >&3

if [ -f /etc/devscripts.conf ]; then
    egrep '^[^#]' /etc/devscripts.conf >&3
else
    echo "Not present" >&3
fi

printf "\n--- ~/.devscripts ---\n" >&3

if [ -f ~/.devscripts ]; then
    egrep '^[^#]' ~/.devscripts >&3
else
    echo "Not present" >&3
fi
