#!/bin/sh

# Copyright (C) 2018, Antonio Terceiro <terceiro@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

if test "$1" = --installed; then
    debrepro="debrepro"
    shift
else
    debrepro="${0%/*}/../scripts/debrepro.sh"
fi

samples="${0%/*}/debrepro"

setUp() {
    tmpdir=$(mktemp -d)
    log="$tmpdir/log"
}

tearDown() {
    rm -rf "$tmpdir"
}

assertPasses() {
    local rc=0
    "$@" > "$log" 2>&1 || rc=$?
    if [ "$rc" -ne 0 ]; then
        cat "$log"
        fail "command failed: $@ (expected pass)"
    fi
}

assertFails() {
    local rc=0
    "$@" > "$log" 2>&1 || rc=$?
    if [ "$rc" -eq 0 ]; then
        cat "$log"
        fail "command passed: $@ (expected fail)"
    fi
}

test_reproducible() {
    assertPasses $debrepro $samples/reproducible
}

test_unreproducible() {
    assertFails $debrepro $samples/unreproducible
}

. shunit2
