#!/bin/sh

# Copyright (C) 2012, Benjamin Drung <bdrung@debian.org>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

COMMAND="../scripts/licensecheck.pl"
WORKDIR="$(readlink -f "${0%/*}")"

. "${0%/*}/shunit2-helper-functions.sh"

license() {
    cd "$WORKDIR"
    runCommand "licensecheck/$1" "licensecheck/$1: $2" "" 0
}

license2() {
    cd "$WORKDIR"
    runCommand "$1 licensecheck/$2" "licensecheck/$2	$3" "" 0
}

testBeerware() {
    license "beerware.cpp" "Beerware"
}

testBSD() {
    license "bsd-3-clause.cpp" "BSD (3 clause)"
}

testLGPL() {
    license "lgpl-2.1.c" "LGPL (v2.1)"
    license "lgpl-2.1.h" "LGPL (v2.1)"
    license "lgpl-2.s" "LGPL (v2)"
}

testGPL() {
    license "gpl-1" "GPL (v1 or later)"
    license "gpl-2" "GPL (v2)"
    license "gpl-2+" "GPL (v2 or later)"
    license "gpl-2+.scm" "GPL (v2 or later)"
    license "gpl-2-comma.sh" "GPL (v2)"
    license "gpl-2-incorrect-address" "GPL (v2) (with incorrect FSF address)"
    license "gpl-3.sh" "GPL (v3)"
    license "gpl-3+" "GPL (v3 or later)"
    license "gpl-3-only.c" "GPL (v3)"
}

testDual() {
    license "dual.c" "Public domain GPL (v3)"
}

testMPL() {
	license "mpl-1.1.sh" "MPL (v1.1)"
	license "mpl-2.0.sh" "MPL (v2.0)"
	license "mpl-2.0-comma.sh" "MPL (v2.0)"
}

testMachine() {
    license2 "-m" "beerware.cpp" "Beerware"
    license2 "--machine" "lgpl-2.1.h" "LGPL (v2.1)"
    license2 "-m --copyright" "gpl-2" "GPL (v2)	2012 Devscripts developers"
}

testFortranComments() {
    license "bsd.f" "BSD (2 clause)"
}

. shunit2
