#!/bin/sh

# Copyright (C) 2018, Antonio Terceiro <terceiro@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -u

ARCHITECTURE="$(dpkg-architecture -qDEB_HOST_ARCH)"
if [ "$ARCHITECTURE" = "hurd-i386" ]; then
    # hurd-i386 lacks sem_open() which is required by something in here
    echo "This test is not supported on $ARCHITECTURE, skipping"
    exit 0
fi

if test "${1:-}" = --installed; then
    debrepro="debrepro --skip filesystem-ordering"
    shift
else
    debrepro="${0%/*}/../scripts/debrepro.sh --skip filesystem-ordering"
fi

samples="${0%/*}/debrepro"

. "${0%/*}/test_helper.sh"

test_reproducible() {
    assertPasses $debrepro $samples/reproducible
}

test_unreproducible() {
    assertFails $debrepro $samples/unreproducible
}

. shunit2
