.TH CVS-DEBC 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
cvs-debc \- view contents of a cvs-buildpackage/cvs-debuild generated package
.SH SYNOPSIS
\fBcvs-debc\fP [\fIoptions\fR] [\fIpackage\fR ...]
.SH DESCRIPTION
\fBcvs-debc\fR is run from the CVS working directory after
\fBcvs-buildpackage\fR or \fBcvs-debuild\fR.  It uses the
\fBcvs-buildpackage\fR system to locate the \fI.changes\fR file
generated in that run.  It then displays information about the .deb
files which were generated in that run, by running \fBdpkg-deb \-I\fR
and \fBdpkg-deb \-c\fR on every \fI.deb\fR archive listed in
the \fI.changes\fR file, assuming that all of the \fI.deb\fR archives
live in the same directory as the \fI.changes\fR file.  It is
useful for ensuring that the expected files have ended up in the
Debian package.
.PP
If a list of packages is given on the command line, then only those
debs with names in this list of packages will be installed.
.PP
Note that unlike \fBcvs-buildpackage\fR, the only way to specify the
source package name is with the \fB\-P\fR option; you cannot simply
have it as the last command-line parameter.
.SH OPTIONS
All current \fBcvs-buildpackage\fR options are silently accepted;
however, only the ones listed below have any effect.  For more details
on all of them, see the \fBcvs-buildpackage\fR(1) manpage.
.TP
\fB\-a\fIdebian-architecture\fR, \fB\-t\fIGNU-system-type\fR
See \fBdpkg-architecture\fR(1) for a description of these options.
They affect the search for the \fI.changes\fR file.  They are provided
to mimic the behaviour of \fBdpkg-buildpackage\fR when determining the
name of the \fI.changes\fR file.
.TP
.BR \-M<module>
The name of the CVS module.
.TP
.BR \-P<package>
The name of the package.
.TP
.B \-V<version>
The version number of the package.
.TP
.B \-T<tag>
The CVS tag to use for exporting sources.
.TP
.B \-R<root\ directory>
Root of the original sources archive.
.TP
.B \-W<work directory>
The full path name for the cvs-buildpackage working directory.
.TP
.B \-x<prefix>
This option provides the CVS default module prefix.
.TP
\fB\-\-help\fR, \fB\-\-version\fR
Show help message and version information respectively.
.SH "SEE ALSO"
.BR cvs-buildpackage (1),
.BR cvs-debi (1),
.BR cvs-debuild (1)
and
.BR debc (1).
.SH AUTHOR
\fBcvs-buildpackage\fR was written by Manoj Srivastava, and the
current version of \fBdebi\fR was written by Julian Gilbey
<jdg@debian.org>.  They have been combined into this program by
Julian Gilbey.
