.TH DEBSIGN 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
debsign \- sign a Debian changes and dsc file pair using GPG/PGP
.SH SYNOPSIS
\fBdebsign\fR [options] [\fIchanges-file\fR|\fIdsc-file\fR]
.SH DESCRIPTION
\fBdebsign\fR mimics the signing aspects (and bugs) of
\fBdpkg-buildpackage\fR(1).  It takes either an unsigned \fI.dsc\fR
file or an unsigned \fI.changes\fR file (along with the associated
unsigned \fI.dsc\fR file found by replacing the architecture name and
\fI.changes\fR by \fI.dsc\fR if it appears in the \fI.changes\fR
file), and signs them using the GNU Privacy Guard or PGP.  It is
careful to calculate the size and MD5 sum of the newly signed
\fI.dsc\fR file and replace the original values in the \fI.changes\fR
file.
.PP
If a \fI.changes\fR or \fI.dsc\fR file is specified, it is signed,
otherwise, \fIdebian/changelog\fR is parsed to determine the name of
the \fI.changes\fR file to look for in the parent directory.
.PP
This utility is useful if a developer must build a package on one
machine where it is unsafe to sign it; they need then only transfer
the small \fI.dsc\fR and \fI.changes\fR files to a safe machine and
then use the \fBdebsign\fR program to sign them before
transferring them back.  This process can be automated in two ways.
If the files to be signed live on the remote machine, the \fB\-r\fR
option may be used to copy them to the local machine and back again
after signing.  If the files live on the local machine, then they may
be transferred to the remote machine for signing using
\fBdebrsign\fR(1).
.PP
This program can take default settings from the \fBdevscripts\fR
configuration files, as described below.
.SH OPTIONS
.TP
.B \-r \fR[\fIusername\fB@\fR]\fIremotehost\fR
The \fI.changes\fR and \fI.dsc\fR files live on the specified remote
host.  In this case, a \fI.changes\fR file must be explicitly named,
with an absolute directory or one relative to the remote home
directory.  SSH will be used for the copying.  The
\fR[\fIusername\fB@\fR]\fIremotehost\fB:\fIchanges\fR syntax is
permitted as an alternative.
.TP
.B \-p\fIprogname\fR
\fIprogname\fR is one of \fBpgp\fR or \fBgpg\fR, and specifies which
signing program is to be called.  The default is \fBgpg\fR if
\fI~/.gnupg/secring.gpg\fR exists and \fBpgp\fR otherwise.
.TP
.B \-m\fImaintainer\fR
Specify the maintainer name to be used for signing.  (See
\fBdpkg-buildpackage\fR(1) for more information about the differences
between \fB\-m\fR, \fB\-e\fR and \fB\-k\fR when building packages;
\fBdebsign\fR makes no use of these distinctions except with respect
to the precedence of the various options.  These multiple options are
provided so that the program will behave as expected when called by
\fBdebuild\fR(1).)
.TP
.B \-e\fImaintainer\fR
Same as \fB\-m\fR but takes precedence over it.
.TP
.B \-k\fIkeyid\fR
Specify the key ID to be used for signing; overrides any \fB\-m\fR
and \fB\-e\fR options.
.TP
\fB\-spgp\fR, \fB\-sgpg\fR
Whether the signing program is to be called with command line
arguments like those of \fBpgp\fR or \fBgpg\fR.
.TP
\fB\-S\fR
Look for a source-only \fI.changes\fR file instead of a binary-build
changes file.
.TP
\fB\-a\fIdebian-architecture\fR, \fB\-t\fIGNU-system-type\fR
See \fBdpkg-architecture\fR(1) for a description of these options.
They affect the search for the \fI.changes\fR file.  They are provided
to mimic the behaviour of \fBdpkg-buildpackage\fR when determining the
name of the \fI.changes\fR file.
.TP
\fB\-\-no-conf\fR, \fB\-\-noconf\fR
Do not read any configuration files.  This can only be used as the
first option given on the command-line.
.TP
.BR \-\-help ", " \-h
Display a help message and exit successfully.
.TP
.B \-\-version
Display version and copyright information and exit successfully.
.SH "CONFIGURATION VARIABLES"
The two configuration files \fI/etc/devscripts.conf\fR and
\fI~/.devscripts\fR are sourced in that order to set configuration
variables.  Command line options can be used to override configuration
file settings.  Environment variable settings are ignored for this
purpose.  The currently recognised variables are:
.TP
.B DEBSIGN_PROGRAM
Setting this is equivalent to giving a \fB\-p\fR option.
.TP
.B DEBSIGN_SIGNLIKE
This must be \fIgpg\fR or \fIpgp\fR and is equivalent to using either
\fB\-sgpg\fR or \fB\-spgp\fR respectively.
.TP
.B DEBSIGN_MAINT
This is the \fB\-m\fR option.
.TP
.B DEBSIGN_KEYID
And this is the \fB\-k\fR option.
.SH "SEE ALSO"
.BR debrsign (1),
.BR dpkg-buildpackage (1),
.BR dpkg-architecture (1),
.BR debuild (1),
.BR md5sum (1),
.BR gpg (1),
.BR pgp (1)
and
.BR devscripts.conf (5).
.SH AUTHOR
This program was written by Julian Gilbey <jdg@debian.org> and is
copyright under the GPL, version 2 or later.
