.TH DPKG-GENBUILDDEPS 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
dpkg-genbuilddeps \- generate a list of packages used to build this package
.SH SYNOPSIS
\fBdpkg-genbuilddeps\fR [\fIarg\fR ...]
.SH DESCRIPTION
This program is a wrapper around \fBdpkg-depcheck\fR(1).  It should be
 run from the top of a Debian build tree.  It calls
\fBdpkg-buildpackage\fR with any arguments given on the command line,
and by tracing the execution of this, it determines which
non-essential packages were used during the package building.  This
can be useful in determining what the \fIBuild-Depends\fR control
fields should contain.  It does not determine which packages were used
for the arch independent parts of the build and which for the arch
dependent parts, not does it attempt to determine which versions of
packages are required.  It should be able to run under \fBfakeroot\fR
rather than being run as root, as \fBfakeroot dpkg-genbuilddeps\fR, or
\fBdpkg-genbuilddeps -rfakeroot\fR.
.PP
This program requires the build-essential package to be installed.  If
it is not, please use \fBdpkg-depcheck\fR directly, with a command
such as
.nf
  dpkg-depcheck --all dpkg-buildpackage -us -uc -b -rfakeroot ...
.fi
All this program itself does is essentially to run the command:
.nf
  dpkg-depcheck -b dpkg-buildpackage -us -uc -b -rfakeroot [arg ...]
.fi
.SH "SEE ALSO"
.B The Debian Policy Manual,
sections on Build-Depends etc.,
.BR dpkg-depcheck (1)
and
.BR fakeroot (1).
.SH AUTHOR
The original \fBdpkg-genbuilddeps\fR was written by Ben Collins
<bcollins@debian.org>.  The current version is a simple wrapper around
\fBdpkg-depcheck\fR written by Bill Allombert <ballombe@debian.org>.
This manual page was written by Julian Gilbey <jdg@debian.org>.
