.TH DEBRSIGN 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
debrsign \- remotely sign a Debian changes and dsc file pair using SSH
.SH SYNOPSIS
\fBdebrsign\fR [options] [\fIuser@\fR]\fIremotehost\fR
[\fIchanges-file\fR|\fIdsc-file\fR]
.SH DESCRIPTION
\fBdebrsign\fR takes either an unsigned \fI.dsc\fR file or an
unsigned \fI.changes\fR file and the associated unsigned \fI.dsc\fR
file (found by replacing the architecture name and \fI.changes\fR
by \fI.dsc\fR) if it appears in the \fI.changes\fR file and signs them
by copying them to the remote machine using \fBssh\fR(1) and remotely
running \fBdebsign\fR(1) on that machine.  All options not listed
below are passed to the \fBdebsign\fR program on the remote machine.
.PP
If a \fI.changes\fR or \fI.dsc\fR file is specified, it is signed,
otherwise, \fIdebian/changelog\fR is parsed to determine the name of
the \fI.changes\fR file to look for in the parent directory.
.PP
This utility is useful if a developer must build a package on one
machine where it is unsafe to sign it; they need then only transfer
the small \fI.dsc\fR and \fI.changes\fR files to a safe machine and
then use the \fBdebsign\fR program to sign them before
transferring them back.  This program automates this process.
.PP
To do it the other way round, that is to connect to an unsafe machine
to download the \fI.dsc\fR and \fI.changes\fR files, to sign them
locally and then to transfer them back, see the \fBdebsign\fR(1)
program, which can do this task.
.SH OPTIONS
.TP
\fB\-S\fR
Look for a source-only \fI.changes\fR file instead of a binary-build
changes file.
.TP
\fB\-a\fIdebian-architecture\fR, \fB\-t\fIGNU-system-type\fR
See \fBdpkg-architecture\fR(1) for a description of these options.
They affect the search for the \fI.changes\fR file.  They are provided
to mimic the behaviour of \fBdpkg-buildpackage\fR when determining the
name of the \fI.changes\fR file.
.TP
\fB\-\-path \fIremote-path\fR
Specify a path to the GPG or PGP binary on the remote host.
.TP
\fB\-\-help\fR, \fB\-\-version\fR
Show help message and version information respectively.
.TP
\fBOther options\fR
All other options are passed on to \fBdebsign\fR on the remote
machine.
.SH "CONFIGURATION VARIABLES"
The two configuration files \fI/etc/devscripts.conf\fR and
\fI~/.devscripts\fR are sourced in that order to set configuration
variables.  Command line options can be used to override configuration
file settings.  Environment variable settings are ignored for this
purpose.  The currently recognised variables are:
.TP
.B DEBRSIGN_PGP_PATH
Equivalent to passing \fB\-\-path\fR on the command line (see above.)
.SH "SEE ALSO"
.BR debsign (1),
.BR dpkg-architecture (1)
and
.BR ssh (1).
.SH AUTHOR
This program was written by Julian Gilbey <jdg@debian.org> and is
copyright under the GPL, version 2 or later.
