.TH EDIT-PATCH "1" "Debian Utilities" "DEBIAN"
.SH NAME
\fBedit-patch\fR, \fBadd-patch\fR \- tool for preparing patches for Debian
source packages

.SH SYNOPSIS
\fBedit-patch\fR <path to patch>

\fBadd-patch\fR <path to patch>

.SH DESCRIPTION
\fBedit-patch\fR is a wrapper script around the quilt, cdbs, and dpatch patch
systems. It simplifies the process of preparing and editing patches to Debian
source packages and allows the user to not have to be concerned with which patch
system is in use.
Run from inside the root directory of the source package, \fBedit-patch\fR can
be used to edit existing patches located in /debian/patches.

It can also be used to incorporate new patches.
If pointed at a patch not already present, it will copy the patch to
/debian/patches in the correct format for the patch system in use.
Next, the patch is applied and a subshell is opened in order to edit the patch.
Typing "exit" or pressing Ctrl-d will close the subshell and launch an editor
to record the debian/changelog entry.

\fBedit-patch\fR is integrated with the bzr and git version control systems.
The patch will be automatically added to the tree, and the debian/changelog
entry will be used as the commit message.

If no patch system is present, the patch is applied inline,
and a copy is stored in debian/patches-applied.

\fBadd-patch\fR is the non-interactive version of \fBedit-patch\fR.
The patch will be incorporated but no editor or subshell will be
spawned.

.SH AUTHORS
\fBedit-patch\fR was written by Daniel Holbach <daniel.holbach@canonical.com>,
Michael Vogt <michael.vogt@canonical.com>, and David Futcher <bobbo@ubuntu.com>.

This manual page was written by Andrew Starr-Bochicchio <a.starr.b@gmail.com>.
.PP
Both are released under the terms of the GNU General Public License, version 3.
