.TH CVS-DEBUILD 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
cvs-debuild \- build a Debian package using cvs-buildpackage and debuild
.SH SYNOPSIS
\fBcvs-debuild\fR [\fIdebuild options\fR] [\fIcvs-buildpackage options\fR]
[\fB\-\-lintian-opts\fR \fIlintian options\fR]
.SH DESCRIPTION
\fBcvs-debuild\fR is a wrapper around \fBcvs-buildpackage\fR to run it
with \fBdebuild\fR as the package-building program.  (This cannot
simply be accomplished using the \fB\-C\fR option of
\fBcvs-buildpackage\fR, as it does not know how to handle all of the
special \fBdebuild\fR options.)
.PP
The program simply stashes the \fBdebuild\fR and \fBlintian\fR
options, and passes them to \fBdebuild\fR when it is
called by \fBcvs-buildpackage\fR.  All of the standard \fBdebuild\fR
options may be used (as listed below), but note that the root command
specified by any \fB\-\-rootcmd\fR or \fB\-r\fR command-line option
will be passed as an option to \fBcvs-buildpackage\fR.  The first
non-\fBdebuild\fR option detected will signal the start of the
\fBcvs-buildpackage\fR options.
.PP
The selection of the root command is slightly subtle: if there are any
command-line options, these will be used.  If not, then if
\fBcvs-buildpackage\fR is set up to use a default root command, that
will be used.  Finally, if neither of these are the case, then
\fBdebuild\fR will use its procedures to determine an appropriate
command, as described in its documentation.
.PP
See the manpages for \fBdebuild\fR(1) and \fBcvs-buildpackage\fR for
more information about the behaviour of each.
.SH "OPTIONS"
The following are the \fBdebuild\fR options recognised by
\fBcvs-debuild\fR.  All \fBcvs-buildpackage\fR and \fBlintian\fR
options are simply passed to the appropriate program.  For
explanations of the meanings of these variables, see
\fBdebuild\fR(1).
.TP
.B \-\-no\-conf\fR, \fB\-\-noconf
.TP
.BI \-\-rootcmd= "gain-root-command\fR, \fP" \-r gain-root-command
.TP
.B \-\-preserve\-env
.TP
.BI \-\-preserve\-envvar= "var\fR, \fP" \-e var
.TP
.BI \-\-set\-envvar= var = "value\fR, \fP" \-e var = value
.TP
.B \-\-lintian\fR, \fB\-\-no\-lintian
.TP
\fB\-\-ignore-dirname\fR, \fB\-\-check-dirname\fR
These should not be needed, but it is provided nevertheless.
.SH "SEE ALSO"
.BR cvs-buildpackage (1),
.BR debuild (1),
.BR dpkg-buildpackage (1),
.BR lintian (1)
.SH AUTHOR
This program was written by Julian Gilbey <jdg@debian.org>.
