.TH CVS-DEBC 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
cvs-debrelease \- upload a cvs-buildpackage/cvs-debuild generated package
.SH SYNOPSIS
\fBcvs-debrelease\fP [\fIcvs-debrelease options\fR] [\fB\-\-dopts\fR
[\fIdupload/dput options\fR]]
.SH DESCRIPTION
\fBcvs-debrelease\fR is run from the CVS working directory after
\fBcvs-buildpackage\fR or \fBcvs-debuild\fR.  It uses the
\fBcvs-buildpackage\fR system to locate the \fI.changes\fR file
generated in that run.  It then uploads the package using
\fBdebrelease\fR(1), which in turn calls either \fBdupload\fR or
\fBdput\fR.  Note that the \fB\-\-dopts\fR option must be specified to
distinguish the \fBcvs-debrelease\fR options from the \fBdupload\fR or
\fBdput\fR options.  Also, the \fBdevscripts\fR configuration files
will be read, as described in the \fBdebrelease\fR(1) manpage.
.PP
Note that unlike \fBcvs-buildpackage\fR, the only way to specify the
source package name is with the \fB\-P\fR option; you cannot simply
have it as the last command-line parameter.
.SH OPTIONS
All current \fBcvs-buildpackage\fR options are silently accepted;
however, only the ones listed below have any effect.  For more details
on all of them, see the \fBcvs-buildpackage\fR(1) manpage.  All
\fBdebrelease\fR options (as listed below) are also accepted.
.TP
\fB\-\-dupload\fR, \fB\-\-dput\fR
This specifies which uploader program to use; the default is
\fBdupload\fR.
.TP
\fB\-a\fIdebian-architecture\fR, \fB\-t\fIGNU-system-type\fR
See \fBdpkg-architecture\fR(1) for a description of these options.
They affect the search for the \fI.changes\fR file.  They are provided
to mimic the behaviour of \fBdpkg-buildpackage\fR when determining the
name of the \fI.changes\fR file.
.TP
.BR \-M\fImodule
The name of the CVS module.
.TP
.BR \-P\fIpackage
The name of the package.
.TP
.B \-V\fIversion
The version number of the package.
.TP
.B \-T\fItag
The CVS tag to use for exporting sources.
.TP
.B \-R\fIroot\ directory
Root of the original sources archive.
.TP
.B \-W\fIwork directory
The full path name for the cvs-buildpackage working directory.
.TP
.B \-x\fIprefix
This option provides the CVS default module prefix.
.TP
\fB\-\-no-conf\fR, \fB\-\-noconf\fR
Do not read any configuration files.  This can only be used as the
first option given on the command-line.
.TP
\fB\-\-help\fR, \fB\-\-version\fR
Show help message and version information respectively.
.SH "SEE ALSO"
.BR cvs-buildpackage (1),
.BR cvs-debuild (1),
.BR debrelease (1)
.SH AUTHOR
\fBcvs-buildpackage\fR was written by Manoj Srivastava, and the
current version of \fBdebrelease\fR was written by Julian Gilbey
<jdg@debian.org>.  They have been combined into this program by
Julian Gilbey.
