.\" for manpage-specific macros, see man(7)
.TH DEBSNAP 1 "January 8, 2009" "Debian devscripts" "DebSnap User Manual"
.SH NAME
debsnap \- retrieve old snapshots of Debian packages

.SH SYNOPSIS
.B debsnap
.RI [ options ] " package " [ version ]

.B debsnap
.RB [ -h " | " \-\-help ] " " [ \-\-version ]


.SH DESCRIPTION
\fBdebsnap\fP is a tool to help with retrieving snapshots of old packages from
a daily archive repository.

The only publicly available snapshot archive is currently located at
\fIhttp://snapshot.debian.net\fP

By default, debsnap will download all the available versions for \fIpackage\fP
that are found in the snapshot archive.  If a \fIversion\fP is specified, only
that particular version will be downloaded, if available.


.SH OPTIONS
The following options are available:

.TP
.BI -d " destination\fR,\fP " \-\-destdir " destination"
Directory to place retrieved packages.

.TP
.BR \-f ", " \-\-force
Force overwriting an existing \fIdestination\fP.  By default \fBdebsnap\fP will
insist the destination directory does not exist yet unless it is explicitly
specified to be '.' (the current working directory).  This is to avoid files
being accidentally overwritten by what is fetched from the archive and to
provide a guarantee for other scripts that only the files fetched will be
present there upon completion.  Note that this option will remove the
\fIdestination\fP directory and all of its contents prior to beginning the
download.

.TP
.BR \-v ", " \-\-verbose
Report on the \fBdebsnap\fP configuration being used and progress during the
download operation.  Please always use this option when reporting bugs.

.TP
.BR \-h ", " \-\-help
Show a summary of these options.

.TP
.B \-\-version
Show the version of \fBdebsnap\fP.


.SH CONFIGURATION OPTIONS
\fBdebsnap\fP may also be configured through the use of the following options
in the devscripts configuration files:

.TP
.B DEBSNAP_VERBOSE
Same as the command line option \fB\-\-verbose\fP.  Set to "yes" to enable.

.TP
.B DEBSNAP_DESTDIR
Set a default path for the destination directory.  If unset
\fI./source\-<package_name>\fP will be used.  The command line option
\fB\-\-destdir\fP will override this.

.TP
.B DEBSNAP_BASE_URL
The base url for the snapshots archive.  This is the root of a directory tree
such as \fIpool/<initial>/<package>/\fP under which a \fISources.gz\fP may be
found, and the root for the location of the packages specified in the
\fISources.gz\fP file found there.

If unset this defaults to \fIhttp://snapshot.debian.net/archive/\fP

.TP
.B DEBSNAP_CLEAN_REGEX
A sed regular expression to transform the directory returned by
`\fBapt\-cache showsrc\fP \fIpackage\fP \fB| grep ^Directory\fP` to a suitable
path to be put between \fBDEBSNAP_BASE_URL\fP and \fBDEBSNAP_SOURCES_GZ_PATH\fP.

If unset it will default to s@\e([^/]*\e)/[^/]*/\e(\&.*\e)@\e1/\e2@
.br
i.e. it transforms \fIpool/<component>/<initial>/<package>\fP into
\fIpool/<initial>/<package>\fP

.TP
.B DEBSNAP_SOURCES_GZ_PATH
The final path to the \fISources.gz\fP file.  This is appended after the
\fBDEBSNAP_BASE_URL\fP and the path modified by \fBDEBSNAP_CLEAN_REGEX\fP to
locate the \fISources.gz\fP file for the package to download.

If unset it will default to \fIsource/Sources.gz\fP


.SH EXIT STATUS
\fBdebsnap\fP will return an exit status of 0 if all operations succeeded,
1 if a fatal error occurred, and 2 if some packages failed to be downloaded
but operations otherwise succeeded as expected.  In some cases packages may
fail to be downloaded because they are no longer available on the snapshot
mirror, so any caller should expect this may occur in normal use.


.SH FILES
.TP
.I /etc/devscripts.conf
Global devscripts configuration options.  Will override hardcoded defaults.
.TP
.I ~/.devscripts
Per\-user configuration options.  Will override any global configuration.


.SH SEE ALSO
.BR devscripts (1),
.BR devscripts.conf (5),
.BR git-debimport (1)


.SH AUTHORS
David Paleino <d.paleino@gmail.com>
.br
Ron Lee <ron@debian.org>

.SH COPYRIGHT
Copyright \(co 2009 David Paleino, Ron Lee

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 3 or (at your option)
any later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can
be found in \fI/usr/share/common\-licenses/GPL\fP.


.SH BUGS
.SS Reporting bugs
The program is part of the devscripts package.  Please report bugs using
`\fBreportbug devscripts\fP`

.\" for manpage-specific macros, see man(7)
.TH DEBSNAP 1 "January 8, 2009" "Debian devscripts" "DebSnap User Manual"
.SH NAME
debsnap \- retrieve old snapshots of Debian packages

.SH SYNOPSIS
.B debsnap
.RI [ options ] " package " [ version ]

.B debsnap
.RB [ -h " | " \-\-help ] " " [ \-\-version ]


.SH DESCRIPTION
\fBdebsnap\fP is a tool to help with retrieving snapshots of old packages from
a daily archive repository.

The only publicly available snapshot archive is currently located at
\fIhttp://snapshot.debian.net\fP

By default, debsnap will download all the available versions for \fIpackage\fP
that are found in the snapshot archive.  If a \fIversion\fP is specified, only
that particular version will be downloaded, if available.


.SH OPTIONS
The following options are available:

.TP
.BI -d " destination\fR,\fP " \-\-destdir " destination"
Directory to place retrieved packages.

.TP
.BR \-f ", " \-\-force
Force overwriting an existing \fIdestination\fP.  By default \fBdebsnap\fP will
insist the destination directory does not exist yet unless it is explicitly
specified to be '.' (the current working directory).  This is to avoid files
being accidentally overwritten by what is fetched from the archive and to
provide a guarantee for other scripts that only the files fetched will be
present there upon completion.  Note that this option will remove the
\fIdestination\fP directory and all of its contents prior to beginning the
download.

.TP
.BR \-v ", " \-\-verbose
Report on the \fBdebsnap\fP configuration being used and progress during the
download operation.  Please always use this option when reporting bugs.

.TP
.BR \-h ", " \-\-help
Show a summary of these options.

.TP
.B \-\-version
Show the version of \fBdebsnap\fP.


.SH CONFIGURATION OPTIONS
\fBdebsnap\fP may also be configured through the use of the following options
in the devscripts configuration files:

.TP
.B DEBSNAP_VERBOSE
Same as the command line option \fB\-\-verbose\fP.  Set to "yes" to enable.

.TP
.B DEBSNAP_DESTDIR
Set a default path for the destination directory.  If unset
\fI./source\-<package_name>\fP will be used.  The command line option
\fB\-\-destdir\fP will override this.

.TP
.B DEBSNAP_BASE_URL
The base url for the snapshots archive.  This is the root of a directory tree
such as \fIpool/<initial>/<package>/\fP under which a \fISources.gz\fP may be
found, and the root for the location of the packages specified in the
\fISources.gz\fP file found there.

If unset this defaults to \fIhttp://snapshot.debian.net/archive/\fP

.TP
.B DEBSNAP_CLEAN_REGEX
A sed regular expression to transform the directory returned by
`\fBapt\-cache showsrc\fP \fIpackage\fP \fB| grep ^Directory\fP` to a suitable
path to be put between \fBDEBSNAP_BASE_URL\fP and \fBDEBSNAP_SOURCES_GZ_PATH\fP.

If unset it will default to s@\e([^/]*\e)/[^/]*/\e(\&.*\e)@\e1/\e2@
.br
i.e. it transforms \fIpool/<component>/<initial>/<package>\fP into
\fIpool/<initial>/<package>\fP

.TP
.B DEBSNAP_SOURCES_GZ_PATH
The final path to the \fISources.gz\fP file.  This is appended after the
\fBDEBSNAP_BASE_URL\fP and the path modified by \fBDEBSNAP_CLEAN_REGEX\fP to
locate the \fISources.gz\fP file for the package to download.

If unset it will default to \fIsource/Sources.gz\fP


.SH EXIT STATUS
\fBdebsnap\fP will return an exit status of 0 if all operations succeeded,
1 if a fatal error occurred, and 2 if some packages failed to be downloaded
but operations otherwise succeeded as expected.  In some cases packages may
fail to be downloaded because they are no longer available on the snapshot
mirror, so any caller should expect this may occur in normal use.


.SH FILES
.TP
.I /etc/devscripts.conf
Global devscripts configuration options.  Will override hardcoded defaults.
.TP
.I ~/.devscripts
Per\-user configuration options.  Will override any global configuration.


.SH SEE ALSO
.BR devscripts (1),
.BR devscripts.conf (5),
.BR git-debimport (1)


.SH AUTHORS
David Paleino <d.paleino@gmail.com>
.br
Ron Lee <ron@debian.org>

.SH COPYRIGHT
Copyright \(co 2009 David Paleino, Ron Lee

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 3 or (at your option)
any later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can
be found in \fI/usr/share/common\-licenses/GPL\fP.


.SH BUGS
.SS Reporting bugs
The program is part of the devscripts package.  Please report bugs using
`\fBreportbug devscripts\fP`

