.\" for manpage-specific macros, see man(7)
.TH DEBSNAP 1 "July 3, 2010" "Debian devscripts" "DebSnap User Manual"
.SH NAME
debsnap \- retrieve old snapshots of Debian packages

.SH SYNOPSIS
.B debsnap
.RI [ options ] " package " [ version ]

.B debsnap
.RB [ -h " | " \-\-help ] " " [ \-\-version ]


.SH DESCRIPTION
\fBdebsnap\fP is a tool to help with retrieving snapshots of old packages from
a daily archive repository.

The only publicly available snapshot archive is currently located at
\fIhttp://snapshot.debian.org\fP

By default, debsnap will download all the available versions for \fIpackage\fP
that are found in the snapshot archive.  If a \fIversion\fP is specified, only
that particular version will be downloaded, if available.


.SH OPTIONS
The following options are available:

.TP
.BI -d " destination\fR,\fP " \-\-destdir " destination"
Directory to place retrieved packages.

.TP
.BR \-f ", " \-\-force
Force writing into an existing \fIdestination\fP.  By default \fBdebsnap\fP will
insist the destination directory does not exist yet unless it is explicitly
specified to be '\fB.\fR' (the current working directory).  This is to avoid files
being accidentally overwritten by what is fetched from the archive and to
provide a guarantee for other scripts that only the files fetched will be
present there upon completion.

.TP
.BR \-v ", " \-\-verbose
Report on the \fBdebsnap\fP configuration being used and progress during the
download operation.  Please always use this option when reporting bugs.

.TP
.BR \-\-list
Don't dwnload but just list versions.

.TP
.BR \-\-binary
Download binary packages instead of source packages.

.TP
.BR \-a ", " \-\-architecture
Specify architecture of downloaded binary packages. Implies \fB\-\-binary\fP.
This can be given multiple times in order to download binary packages for
multiple architectures.

.TP
.B \-\-first
Specify the minimum version of a package which will be downloaded.  Any
versions which compare larger than this, according to \fBdpkg\fP, will be
considered for download.  May be used in combination with \fB\-\-last\fP.

.TP
.B \-\-last
Specify the maximum version of a package which will be downloaded.  Any package
versions which compare less than this, according to \fBdpkg\fP, will be
considered for download.  May be used in combination with \fB\-\-first\fP.

.TP
.BR \-h ", " \-\-help
Show a summary of these options.

.TP
.B \-\-version
Show the version of \fBdebsnap\fP.


.SH CONFIGURATION OPTIONS
\fBdebsnap\fP may also be configured through the use of the following options
in the devscripts configuration files:

.TP
.B DEBSNAP_VERBOSE
Same as the command line option \fB\-\-verbose\fP.  Set to \fIyes\fP to enable.

.TP
.B DEBSNAP_DESTDIR
Set a default path for the destination directory.  If unset
\fI./source\-<package_name>\fP will be used.  The command line option
\fB\-\-destdir\fP will override this.

.TP
.B DEBSNAP_BASE_URL
The base url for the snapshots archive.

If unset this defaults to \fIhttp://snapshot.debian.org\fP

.SH EXIT STATUS
\fBdebsnap\fP will return an exit status of 0 if all operations succeeded,
1 if a fatal error occurred, and 2 if some packages failed to be downloaded
but operations otherwise succeeded as expected.  In some cases packages may
fail to be downloaded because they are no longer available on the snapshot
mirror, so any caller should expect this may occur in normal use.

.SH EXAMPLES
.TP
.BR "debsnap -a amd64 xterm 256-1"
Download the binary package of a specific xterm version for amd64 architecture.
.TP
.BR "debsnap -a armel xterm"
Download binary packages for all versions of xterm for armel architecture.
.TP
.BR "debsnap --binary xterm 256-1"
Download binary packages for a specific xterm version but for all architectures.
.TP
.BR "debsnap --binary xterm"
Download binary packages for all versions of xterm for all architectures.
.TP
.BR "aptitude search '~i' -F '%p %V' | while read pkg ver; do debsnap -a $(dpkg-architecture -qDEB_HOST_ARCH) -a all $pkg $ver; done" 
Download binary packages of all packages that are installed on the system.

.SH FILES
.TP
.I /etc/devscripts.conf
Global devscripts configuration options.  Will override hardcoded defaults.
.TP
.I ~/.devscripts
Per\-user configuration options.  Will override any global configuration.

.SH SEE ALSO
.BR devscripts (1),
.BR devscripts.conf (5),
.BR git-debimport (1)

.SH AUTHORS
David Paleino <dapal@debian.org>

.SH COPYRIGHT
Copyright \(co 2010 David Paleino

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 3 or (at your option)
any later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can
be found in \fI/usr/share/common\-licenses/GPL\fP.

.SH BUGS
.SS Reporting bugs
The program is part of the devscripts package.  Please report bugs using
`\fBreportbug devscripts\fP`

