.TH "diff2patches" "1" "" "Raphael Geissert <atomo64@gmail.com>" ""
.SH "NAME"
.LP
diff2patches \- Extract non\-debian/ patches from .diff.gz files
.SH "SYNTAX"
.LP
\fBdiff2patches \fIfilename\fP
.br
\fBdiff2patches \-\-help\fR|\fB\-\-version\fP
.SH "DESCRIPTION"
.LP
Extracts patches from .diff.gz which apply to files outside the
\*(lqdebian/\*(rq directory scope.  A patch is created for each modified file.
Each patch is named according to the path of the modified file, with \*(lq/\*(rq
replaced by \*(lq___\*(rq, and an extension of \*(lq.patch\*(rq.
.SH "OPTIONS"
.LP
.TP 4
\fB\fIfilename\fP\fR
Extract patches from \fB\fIfilename\fP\fR which apply outside the
\*(lqdebian/\*(rq directory.
.TP
\fB\-\-help\fR
Output help information and exit.
.TP
\fB\-\-version\fR
Output version information and exit.
.SH "FILES"
.TP
\fIdebian/control\fP
Existence of this file is tested before any patch is extracted.
.TP
\fIdebian/\fP
.TQ
\fIdebian/patches/\fP
Patches are extracted to one of these directories.  \*(lqdebian/patches/\*(rq is
preferred, if it exists.  If \fIDEB_PATCHES\fP is present in the environment,
it will override this behavior (see \*(lqENVIRONMENT VARIABLES\*(rq section
below).
.SH "ENVIRONMENT VARIABLES"
.TP
\fBDEB_PATCHES\fP
When defined and points to an existing directory, patches are extracted in that directory
and not under \*(lqdebian/\*(rq nor \*(lqdebian/patches/\*(rq.
.SH "SEE ALSO"
.LP
\fBcombinediff\fR(1)
.SH "AUTHOR"
.LP
Raphael Geissert <atomo64@gmail.com>
