.TH DSCEXTRACT 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
dscextract \- extract a single file from a Debian source package
.SH SYNOPSIS
\fBdscextract\fR [\fIoptions\fR] \fIdscfile\fR \fIfile\fR
.SH DESCRIPTION
\fBdscextract\fR reads a single file from a Debian source package.  The idea is
to only look into \fI.diff.gz\fR files (source format 1.0) or \fI.debian.tar.gz/bz2\fR
files (source format 3.0) where possible, hence avoiding to unpack large
tarballs.  It is most useful for files in the \fIdebian/\fR subdirectory.

\fIfile\fP is relative to the first level directory contained in the package,
i.e. with the first component stripped.
.SH OPTIONS
.TP
.B \fB\-f
"Fast" mode. For source format 1.0, avoid to fall back scanning the \fI.orig.tar.gz\fR
file if \fIfile\fR was not found in the \fI.diff.gz\fR.  (For 3.0 packages, it is
assumed that \fIdebian/*\fR are exactly the contents of \fIdebian.tar.gz/bz2\fR.)
.SH "EXIT STATUS"
.TP
0
\fIfile\fR was extracted.
.TP
1
\fIfile\fR was not found in the source package.
.TP
2
An error occurred, like \fIdscfile\fR was not found.
.SH EXAMPLE
dscextract dds_2.1.1+ddd105-2.dsc debian/watch || test $? = 1
.SH AUTHOR
\fBdscextract\fR was written by Christoph Berg <myon@debian.org>.
