.TH MERGECHANGES 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
mergechanges \- merge multiple changes files
.SH SYNOPSIS
\fBmergechanges\fR [\fB\-d\fR] [\fB\-f\fR] [\fB\-i\fR] \fIfile1 file2\fR [\fIfile\fR...]
.SH DESCRIPTION
\fBmergechanges\fR merges two or more \fI.changes\fR files, merging
the Architecture, Description and Files (and Checksums-*, if present)
fields of the two.  There are checks made to ensure that the changes
files are from the same source package and version and use the same
changes file Format.  The first changes file is used as the basis and
the information from the later ones is merged into it.
.PP
The output is normally written to \fIstdout\fR.  If the \fB\-f\fR
option is given, the output is written to
\fIpackage\fR_\fIversion\fR_multi.changes instead, in the same
directory as the first changes file listed.
.PP
If the \fB\-d\fR option is given and the output is generated successfully, the
input files will be deleted.
.PP
If the \fB\-i\fR or \fB\-\-indep\fR option is given, source packages
and architecture-independent (Architecture: all) packages are included
in the output, but architecture-dependent packages are not.
.SH AUTHOR
Gergely Nagy <algernon@debian.org>,
modifications by Julian Gilbey <jdg@debian.org>,
Mark Hymers <mhy@debian.org>,
Adam D. Barratt <adam@adam-barratt.org.uk>, and
Simon McVittie <smcv@debian.org>.
