.TH RC-ALERT 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
rc-alert \- check for installed packages with release-critical bugs
.SH SYNOPSIS
\fBrc\-alert\fR [\fIinclusion options\fR] [\fB\-\-debtags\fR [\fItag\fR[\fB,\fItag\fR ...]] [\fB\-\-popcon\fR] [\fIpackage\fR ...]
.br
\fBrc\-alert \-\-help\fR|\fB\-\-version\fR
.SH DESCRIPTION
\fBrc\-alert\fR downloads the list of release-critical bugs from the
Debian BTS webpages, and then outputs a list of packages installed on
the system, or given on the command-line, which are in that list.
.P
If the directory \fI~/.devscripts_cache\fP exists or the
\fB\-\-cache\fP option is given, then the (sizable) downloaded list
will be cached, and will only be downloaded again on a second
invocation if it has changed.
.SH OPTIONS
.TP
.BR \-\-cache
Force the creation of the \fI~/.devscripts_cache\fP cache directory.
.TP
.BR \-\-help ", " \-h
Show a summary of options.
.TP
.BR \-\-version ", " \-v
Show version and copyright information.
.P
It is also possible to filter the list of bugs reported based on the
tags and distributions associated with the package. The filtering options
are:
.TP
.BR \-\-include\-tags ", " \-f
A list of tags which the bug must have, in the format used for output.
For example, to include bugs tagged security or help wanted, use "SH".
.TP
.BR \-\-include\-tag\-op ", " \-t
If set to \fIand\fP, a bug must have all of the tags specified by
\fB\-\-include\-tags\fP.
.TP
.BR \-\-exclude\-tags
A list of tags which the bug must not have, in the same format as
\fB\-\-include\-tags\fP.
.TP
.BR \-\-exclude\-tag\-op
If set to \fIand\fP, a bug must have none of the tags specified by
\fB\-\-exclude\-tags\fP.  By default, the bug will be excluded if any tag
matches.
.TP
.BR \-\-include\-dists ", " \-d
A list of distributions which the bug must apply to, in the format used for
output.  For example, to include bugs affecting testing or unstable, use "TU".
.TP
.BR \-\-include\-dist\-op ", " \-o
If set to \fIand\fP, a bug must apply to all of the specified distributions in
order to be included.
.TP
.BR \-\-exclude\-dists
A list of distributions to which the bug must not apply, in the same format as
\fB\-\-include\-dists\fP.
.TP
.BR \-\-exclude\-dist\-op
If set to \fIand\fP, a bug must apply to all of the specified distributions
in order to be excluded.  By default the bug will be excluded if it applies
to any of the listed distributions.
.P
It is also possible to only list bugs which have specific debtags set. Note
that you need to have debtags installed and also that it's not mandatory for
maintainers to set proper debtags. The produced list will thus probably be
incomplete.
.TP
.BR \-\-debtags
Match packages based on the listed tags. Each package is matched only if it has
all the listed tags; in the case of multiple tags within the same facet, a
package is matched if it has any of the listed tags within the facet.
.TP
.BR \-\-debtags\-database
Use a non-standard debtags database.  The default is
\fI/var/lib/debtags/packages-tags\fP.
.P
Popularity-contest collects data about installation and usage of Debian
packages. You can additionally sort the bugs by the popcon rank of the related
packages.
.TP
.BR \-\-popcon
Sort bugs by the popcon rank of the package the bug belongs to.
.TP
.BR \-\-pc\-vote
By default, packages are sorted according to the number of people who have the
package installed. This option enables sorting by the number of people
regularly using the package instead. This option has no effect in combination
with \-\-pc\-local.
.TP
.BR \-\-pc\-local
Instead of requesting remote data the information from the last popcon run is
used (\fI/var/log/popularity-contest\fP).
.SH EXAMPLES
.TP
.BR \-\-include\-dists " OS"
The bug must apply to at least one of oldstable or stable
.TP
.BR \-\-include\-dists " TU" " \-\-include\-dist\-op" " and"
The bug must apply to both testing and unstable
.TP
.BR \-\-include\-dists " O" " \-\-include\-tags" " S" " \-\-exclude\-tags" " +"
The bug must apply to oldstable and be tagged security but not patch
.TP
.BR \-\-exclude\-dists " SOT" " \-\-include\-tags" " R"
The bug must apply to only unstable or experimental (or both) and be tagged
unreproducible
.TP
.BR \-\-debtags " implemented-in::perl,role::plugin,implemented-in::python"
The bug must apply to packages matching the specified debtags, i.e. the match
will only include packages that have the 'role::plugin' tag and that have
either of the tags 'implemented-in::perl' or 'implemented-in::python'.
.TP
.BR \-\-popcon " "\-\-pc\-local
Read \fI/var/log/popularity-contest\fP and sort bugs by your personal popcon ranking
(which is basically the atime of your packages' binaries).
.SH BUGS
It is not possible to say "does not apply only to unstable"
.SH SEE ALSO
.BR debtags(1)
.BR popbugs(1)
.BR popularity-contest(8)
.SH AUTHOR
\fBrc-alert\fR was written by Anthony DeRobertis and modified by
Julian Gilbey <jdg@debian.org> and Adam D. Barratt <adam@adam-barratt.org.uk>
for the devscripts package. Debtags and popcon functionality was added by Jan
Hauke Rahm <info@jhr-online.de>.
