.TH WHODEPENDS 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
whodepends \- check which maintainers' packages depend on a package
.SH SYNOPSIS
\fBwhodepends\fP [\fIpackage\fR] [\fIoptions\fR]
.SH DESCRIPTION
\fBwhodepends\fR gives the names, e-mail addresses and the packages they
maintain of all maintainers who have packages depending on the given
package.
.SH OPTIONS
.TP
.B \-\-help\fP, \fB\-h
Show a brief usage message.
.TP
.B \-\-version\fP, \fB\-v
Show version and copyright information.
.SH BUGS
\fBwhodepends\fR is not very efficient.
.SH AUTHOR
\fBwhodepends\fR has been written by Moshe Zadka <moshez@debian.org>.
