.TH WNPP-ALERT 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
wnpp-alert \- check for installed packages up for adoption or orphaned
.SH SYNOPSIS
\fBwnpp-alert [\-\-diff] [package ...]\fR
.br
\fBwnpp-alert \-\-help|\-\-version\fR
.SH DESCRIPTION
\fBwnpp-alert\fR downloads the lists of packages which have been
orphaned (O), are up for adoption (RFA), or the maintainer has asked
for help (RFH) from the WNPP webpages, and then outputs a list of
packages installed on the system, or matching the listed packages,
which are in those lists.
.PP
Note that WNPP, and therefore \fBwnpp-alert\fR's output, is source 
package based.
.SH OPTIONS
.TP
.BR \-\-diff ", " \-d
If the \fI~/.devscripts_cache\fP directory exists, compare the output of
\fBwnpp-alert\fR to the previous output (cached in the file
\fIwnpp-diff\fR) and output the differences.
.TP
.BR \-\-help ", " \-h
Show a summary of options.
.TP
.BR \-\-version ", " \-v
Show version and copyright information.
.SH SEE ALSO
http://www.debian.org/devel/wnpp
.SH AUTHOR
\fBwnpp-alert\fR was written by Arthur Korn <arthur@korn.ch> and
modified by Julian Gilbey <jdg@debian.org> for the devscripts
package.  It is in the public domain.
